### ISSUE TITLE
Error run app

### ISSUE THREAD

**Issue by talesam** [Ahmed-Z/Telegram-Remote-Desktop#1]
I did the configuration as described, but this error is occurring.
```
talesam@jedi:~/Programas/Telegram-Remote-Desktop$ python telegram-remote-desktop.py 
Traceback (most recent call last):
  File "/home/talesam/Programas/Telegram-Remote-Desktop/telegram-remote-desktop.py", line 169, in <module>
    bot = TelegramBot()
  File "/home/talesam/Programas/Telegram-Remote-Desktop/telegram-remote-desktop.py", line 18, in __init__
    auth = json.load(f)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 2 column 24 (char 25)

```

**Comment by Ahmed-Z** [comment]
Please check you `auth.json` file. It should follow this format 

```
{
    "TOKEN":YOUR TOKEN,
    "CHAT_ID": YOUR CHAT ID
}
```

**Comment by talesam** [comment]
Yes:

```
{
    "TOKEN": 5735637280:AAQPZX06ggg2PNCOFjwTZVLw9h2fOtXYhug,
    "CHAT_ID": 19203495
}
```

I changed some characters of my token and key, so I posted it here to see that it's correct.

**Comment by Ahmed-Z** [comment]
The token and chat id must be in string format. And name the file `auth.json`.

```
{
    "TOKEN": "5735637280:AAQPZX06ggg2PNCOFjwTZVLw9h2fOtXYhug",
    "CHAT_ID": "19203495"
}
```

**Comment by talesam** [comment]
```
talesam@jedi:~/Programas/Telegram-Remote-Desktop$ python telegram-remote-desktop.py 
[+] BOT has started
```

Really missing the quotes, thanks!
